# Generated by Django 3.0.1 on 2020-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200106_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Pyszne jedzonko', max_length=300),
            preserve_default=False,
        ),
    ]
